Update code_quality.yml

diff --git a/.github/workflows/code_quality.yml b/.github/workflows/code_quality.yml
--- a/.github/workflows/code_quality.yml
+++ b/.github/workflows/code_quality.yml
@@ -15,33 +15,30 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: 'temurin'
-
       - name: Grant execute permission for gradlew
-        run: chmod +x ./gradlew
+        run: chmod +x gradlew
+        working-directory: Code
 
       - name: Run Detekt
         run: ./gradlew detekt
+        working-directory: Code
 
       - name: Run Ktlint
         run: ./gradlew ktlintCheck
+        working-directory: Code
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v2
         with:
-          projectBaseDir: .
+          projectBaseDir: ./Code
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
       - name: Prepare reports for GitHub Pages
         run: |
           mkdir -p reports
-          cp app/build/reports/detekt/detekt.html reports/detekt.html || echo "Detekt report not found"
-          cp app/build/reports/ktlint/ktlint.html reports/ktlint.html || echo "Ktlint report not found"
+          cp Code/app/build/reports/detekt/detekt.html reports/detekt.html || echo "Detekt report not found"
+          cp Code/app/build/reports/ktlint/ktlint.html reports/ktlint.html || echo "Ktlint report not found"
 
       - name: Publish report to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
@@ -50,3 +47,4 @@ jobs:
           publish_dir: ./reports
           publish_branch: gh-pages
           force_orphan: true
+
